name: evahan
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  http: ^1.3.0
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  youtube_player_flutter: ^9.1.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  android: true
  image_path: images/icon/app_icon.png

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf